modLoader="javafml"
loaderVersion="[2,)"
license="MIT"

[[mods]]
modId="hephafix"
version="1.0.0"
displayName="Hephaestus Forge Fix"
authors="BugsBlind"
description="Automation fix for Hephaestus Forge"

[[dependencies.hephafix]]
    modId="neoforge"
    type="required"
    versionRange="[21,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.hephafix]]
    modId="forbidden_arcanus"
    type="required"
    versionRange="*" # Дозволяємо будь-яку версію, щоб не було конфліктів
    ordering="NONE"
    side="BOTH"
